"""Git pre-push: scan whether key docs moved with the code."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from .sync import check_code_doc_sync

GIT_PREPUSH = """\
#!/bin/sh
# generated by `project hooks install`
ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT" || exit 1
if command -v project >/dev/null 2>&1; then
  exec project hooks run pre-push
fi
if command -v uv >/dev/null 2>&1; then
  exec uv run project hooks run pre-push
fi
echo "project: CLI not found, skip push doc sync" >&2
exit 0
"""

MARKER = "project hooks run file-change"


def _git(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )


def _is_git_repo(root: Path) -> bool:
    proc = _git(root, "rev-parse", "--is-inside-work-tree")
    return proc.returncode == 0 and proc.stdout.strip() == "true"


def _zero_sha(sha: str) -> bool:
    return bool(sha) and set(sha) <= {"0"}


def _diff_names(root: Path, remote_sha: str, local_sha: str) -> list[str]:
    if _zero_sha(local_sha):
        return []
    if _zero_sha(remote_sha):
        proc = _git(
            root, "log", "--pretty=format:", "--name-only", local_sha, "--not", "--remotes"
        )
    else:
        proc = _git(root, "diff", "--name-only", remote_sha, local_sha)
    if proc.returncode != 0 or not proc.stdout.strip():
        return []
    return [
        line.strip().replace("\\", "/")
        for line in proc.stdout.splitlines()
        if line.strip()
    ]


def files_from_pre_push_stdin(root: Path, raw: str) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for line in raw.splitlines():
        parts = line.split()
        if len(parts) < 4:
            continue
        _local_ref, local_sha, _remote_ref, remote_sha = parts[:4]
        for name in _diff_names(root, remote_sha, local_sha):
            if name not in seen:
                seen.add(name)
                out.append(name)
    return out


def files_vs_upstream(root: Path) -> list[str]:
    for spec in ("@{u}...HEAD", "origin/HEAD...HEAD"):
        proc = _git(root, "diff", "--name-only", spec)
        if proc.returncode == 0:
            return [
                line.strip().replace("\\", "/")
                for line in proc.stdout.splitlines()
                if line.strip()
            ]
    return []


def install_hooks(root: Path) -> list[str]:
    if not _is_git_repo(root):
        raise FileNotFoundError(f"{root} 不是 git 仓库，无法部署 git hook（先 git init）")
    dest = root / ".githooks"
    dest.mkdir(parents=True, exist_ok=True)
    path = dest / "pre-push"
    path.write_text(GIT_PREPUSH, encoding="utf-8", newline="\n")
    try:
        path.chmod(path.stat().st_mode | 0o111)
    except OSError:
        pass
    stale = dest / "pre-commit"
    actions: list[str] = []
    if stale.exists():
        stale.unlink()
        actions.append("removed .githooks/pre-commit")
    proc = _git(root, "config", "core.hooksPath", ".githooks")
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or "git config core.hooksPath 失败")
    actions += [
        "wrote .githooks/pre-push → 推送时扫描关键文档是否随代码更新",
        "git config core.hooksPath .githooks",
    ]
    actions.extend(_strip_claude_filechange_hook(root))
    return actions


def _strip_claude_filechange_hook(root: Path) -> list[str]:
    settings = root / ".claude" / "settings.json"
    if not settings.exists():
        return []
    try:
        data = json.loads(settings.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []
    hooks = data.get("hooks")
    if not isinstance(hooks, dict) or "PostToolUse" not in hooks:
        return []
    post = hooks.get("PostToolUse") or []
    kept = [item for item in post if MARKER not in json.dumps(item)]
    if len(kept) == len(post):
        return []
    if kept:
        hooks["PostToolUse"] = kept
    else:
        del hooks["PostToolUse"]
    if not hooks:
        data.pop("hooks", None)
    if data:
        settings.write_text(
            json.dumps(data, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    else:
        settings.unlink()
    return ["removed Claude Code PostToolUse file-change"]


def hook_status(root: Path) -> dict:
    git_ok = False
    if _is_git_repo(root):
        proc = _git(root, "config", "--get", "core.hooksPath")
        git_ok = (root / ".githooks" / "pre-push").exists() and (
            proc.stdout.strip() == ".githooks"
        )
    return {"git_pre_push": git_ok, "installed": git_ok}


def run_pre_push(
    root: Path, *, files: list[str] | None = None, stdin: str = ""
) -> list:
    if files:
        changed = files
    elif stdin.strip():
        changed = files_from_pre_push_stdin(root, stdin)
    else:
        changed = files_vs_upstream(root)
    return check_code_doc_sync(changed)
